### ISSUE TITLE
IP地址输入框的输入长度有点问题

### ISSUE THREAD

**Issue by cooguyan** [2512500960/zzurj#1]
配置ip地址的时候每一栏只能输入两位。比如：**10.106.xx.xx** 
其中106的6打不出来 :)

**Comment by 2512500960** [comment]
> 配置ip地址的时候每一栏只能输入两位。比如：**10.106.xx.xx**
> 其中106的6打不出来 :)

这个修改过的客户端我不在维护了
这个bug我看原来的老破解客户端好像也有，
你可以先把错误的ip输入进去，先点一个确定，软件会把ip和密码用户名等存到一个config.ini文件中，然后关掉软件，手动修改这个config.ini里面的ip再打开就可以了
![D~)AN 5 G9D(F@X7JZRL6(J](https://user-images.githubusercontent.com/16852896/54203529-6309f880-450d-11e9-99b5-d3e406fb2ae1.png)

**Comment by 2512500960** [comment]
还是不行的话可以加我q,github的名字就是我的qq（如果是北区的就别加了，北区的有心跳包机制，我没有样本）

**Comment by waytrue** [comment]
学长能不能弄个mentohust  您的minieap在openwrt 树莓派3b+上会报错 [图片]

**Comment by waytrue** [comment]
![ZE@SX{H2QTJKOOHWBDH0R](https://user-images.githubusercontent.com/37917024/54286981-cbc1a580-45df-11e9-9a70-5c19a799c461.png)

**Comment by cooguyan** [comment]
> 还是不行的话可以加我q,github的名字就是我的qq（如果是北区的就别加了，北区的有心跳包机制，我没有样本）

我就是北区的，现在已经用上了。不过没有你说的心跳包问题，一天了也没有掉线😃。
另外我试了下从剪贴板直接粘贴也可以输入三位数

**Comment by waytrue** [comment]
学长不用了 我把mentohust编出来了
