### ISSUE TITLE
这个是干嘛用的？是用来共享热点吗？还是不需要账号密码就可以登陆

### ISSUE THREAD

**Issue by xinkecn** [2512500960/zzurj#3]
求问

**Comment by 2512500960** [comment]
> 求问

学校官网上的原版锐捷客户端，开热点（客户端会检测到多网卡）之后应该会断开连接。这个是代替那个客户端的，不会因为开热点掉线。不知道现在学校里面升级了没有。

**Comment by xinkecn** [comment]
> > 求问
> 
> 学校官网上的原版锐捷客户端，开热点（客户端会检测到多网卡）之后应该会断开连接。这个是代替那个客户端的，不会因为开热点掉线。不知道现在学校里面升级了没有。

了解，正需要这个呢，不能开热点整的好烦人。
另外问一下可以在openwrt路由器上运行么？直接用路由器共享出来

**Comment by 2512500960** [comment]
> > > 求问
> > 
> > 
> > 学校官网上的原版锐捷客户端，开热点（客户端会检测到多网卡）之后应该会断开连接。这个是代替那个客户端的，不会因为开热点掉线。不知道现在学校里面升级了没有。
> 
> 了解，正需要这个呢，不能开热点整的好烦人。
> 另外问一下可以在openwrt路由器上运行么？直接用路由器共享出来

另外一个叫做minieap的软件是可以在linux上运行的，我还在学校的时候是可以用的，现在应该也是可以的。

**Comment by xinkecn** [comment]
好像不能用了，一直在提交用户名

**Comment by 2512500960** [comment]
> 好像不能用了，一直在提交用户名

那不是客户端的问题吧，先考虑wincap装了没有，以及网络接口选对了没有。

**Comment by 2512500960** [comment]
> 好像不能用了，一直在提交用户名

还有啊，郑大不是放假了吗，你也不在学校吧。

**Comment by xinkecn** [comment]
> > 好像不能用了，一直在提交用户名
> 
> 还有啊，郑大不是放假了吗，你也不在学校吧。

留校了，现在还在学校。
![2345截图20210113233256](https://user-images.githubusercontent.com/37695244/104473209-b06abb80-55f7-11eb-9c96-0acf42004a4d.png)
设置都是默认的，wincap已经装了，可能是软件不能识别网卡，学校的客户端和这个客户端识别出来的网卡不一样。

**Comment by 2512500960** [comment]
你选的什么网卡

**Comment by xinkecn** [comment]
![image](https://user-images.githubusercontent.com/37695244/104474307-d775bd00-55f8-11eb-9508-bb4e501994f4.png)



![image](https://user-images.githubusercontent.com/37695244/104474576-1ad02b80-55f9-11eb-9d6d-103734c2a325.png)
一个是学校的客户端一个是破解的

**Comment by xinkecn** [comment]
![image](https://user-images.githubusercontent.com/37695244/104475428-0e000780-55fa-11eb-9acc-e83980170753.png)

**Comment by 2512500960** [comment]
qq远程看下？

**Comment by 2512500960** [comment]
有空儿加个qq远程看看吧
