### ISSUE TITLE
发送用户名超时，并且认证mac地址和本机mac地址不一样

### ISSUE THREAD

**Issue by lhumanfy** [2512500960/zzurj#4]
网卡选择应该没错
![Inked146660330-af3d6b19-9db4-4f3d-aa60-01397846be8f](https://user-images.githubusercontent.com/57166664/146669474-39764097-ec33-4c5a-95a6-7f539ef70069.jpg)
![Inked146660339-02d8ed43-b8db-44e3-b66b-20af61273106](https://user-images.githubusercontent.com/57166664/146669476-2cdf5ca3-d913-4128-8795-63f48ceda8ec.jpg)

**Comment by 2512500960** [comment]
抓包分析下，

**Comment by 2512500960** [comment]
或者加qq远程

**Comment by wowstyle** [comment]
同样问题，现在解决了么？
虽然校园网免费使用，但是开启Hyper-V 之后锐捷报错，但又想用Ubuntu lts，哭唧唧

**Comment by 2512500960** [comment]
> 同样问题，现在解决了么？ 虽然校园网免费使用，但是开启Hyper-V 之后锐捷报错，但又想用Ubuntu lts，哭唧唧

这个windows下的客户端应该是用不了了（代码有错误，跟用户名长度有关系），我也不在学校不想改了，想办法儿用linux下的客户端吧。

**Comment by lhumanfy** [comment]
> 问题现在 校园网免费使用，开启Hyper-V之后的锐捷报错，但又想用Ubuntu lts，哭唧唧唧呢？

linux版本的可用，装双系统，或者整个可以刷Padavan等固件的路由器，路由器里面运行即可。
