### ISSUE TITLE
这个项目还能用不

### ISSUE THREAD

**Issue by lingyan12** [2512500960/zzurj#7]
这个项目还能用不 请问这个项目现在还能用不

**Comment by 2512500960** [comment]
听同学说北区还能用，新区不行，新区可以考虑用linux下面的那个客户端。

昨天开始想改代码，想让它在新区能用。

**Comment by lingyan12** [comment]
我的天，老哥回复神速呀，好嘞 我去看看你的那个linux那个仓库，谢啦

**Comment by 2512500960** [comment]
详情见readme
